/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 
 *
 * The version of the OpenAPI document: 1.19.28
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ChecksListSortByParameterAllOf
 */
public class ChecksListSortByParameterAllOfTest {
    private final ChecksListSortByParameterAllOf model = new ChecksListSortByParameterAllOf();

    /**
     * Model tests for ChecksListSortByParameterAllOf
     */
    @Test
    public void testChecksListSortByParameterAllOf() {
        // TODO: test ChecksListSortByParameterAllOf
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'sendDate'
     */
    @Test
    public void sendDateTest() {
        // TODO: test sendDate
    }

}
