/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 
 *
 * The version of the OpenAPI document: 1.19.28
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MailType;
import com.konfigthis.client.model.PostcardSize;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Returned
 */
public class ReturnedTest {
    private final Returned model = new Returned();

    /**
     * Model tests for Returned
     */
    @Test
    public void testReturned() {
        // TODO: test Returned
    }

    /**
     * Test the property 'mailType'
     */
    @Test
    public void mailTypeTest() {
        // TODO: test mailType
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'frontOriginalUrl'
     */
    @Test
    public void frontOriginalUrlTest() {
        // TODO: test frontOriginalUrl
    }

    /**
     * Test the property 'backOriginalUrl'
     */
    @Test
    public void backOriginalUrlTest() {
        // TODO: test backOriginalUrl
    }

}
