/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> 
 *
 * The version of the OpenAPI document: 1.19.28
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AddressesListBeforeAfterParameterAllOf;
import com.konfigthis.client.model.ChecksListSortByParameterAllOf;
import com.konfigthis.client.model.Error;
import com.konfigthis.client.model.MailType;
import com.konfigthis.client.model.QrCode;
import com.konfigthis.client.model.SelfMailer;
import com.konfigthis.client.model.SelfMailerDeletion;
import com.konfigthis.client.model.SelfMailerEditable;
import com.konfigthis.client.model.SelfMailerSize;
import com.konfigthis.client.model.SelfMailersGetListResponse;
import com.konfigthis.client.model.SfmUseType;
import com.konfigthis.client.model.Status;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SelfMailersApi
 */
@Disabled
public class SelfMailersApiTest {

    private static SelfMailersApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new SelfMailersApi(apiClient);
    }

    /**
     * Create
     *
     * Creates a new self_mailer given information
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewSelfMailerTest() throws ApiException {
        String description = null;
        Map<String, String> metadata = null;
        MailType mailType = null;
        String mergeVariables = null;
        Object sendDate = null;
        SelfMailerSize size = null;
        Object to = null;
        Object from = null;
        Object inside = null;
        Object outside = null;
        String billingGroupId = null;
        QrCode qrCode = null;
        SfmUseType useType = null;
        Boolean fsc = null;
        String idempotencyKey = null;
        String idempotencyKey2 = null;
        SelfMailer response = api.createNewSelfMailer()
                .description(description)
                .metadata(metadata)
                .mailType(mailType)
                .mergeVariables(mergeVariables)
                .sendDate(sendDate)
                .size(size)
                .to(to)
                .from(from)
                .inside(inside)
                .outside(outside)
                .billingGroupId(billingGroupId)
                .qrCode(qrCode)
                .useType(useType)
                .fsc(fsc)
                .idempotencyKey(idempotencyKey)
                .idempotencyKey2(idempotencyKey2)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve
     *
     * Retrieves the details of an existing self_mailer. You need only supply the unique self_mailer identifier that was returned upon self_mailer creation.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDetailsTest() throws ApiException {
        String sfmId = null;
        SelfMailer response = api.getDetails(sfmId)
                .execute();
        // TODO: test validations
    }

    /**
     * List
     *
     * Returns a list of your self_mailers. The self_mailers are returned sorted by creation date, with the most recently created self_mailers appearing first.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListTest() throws ApiException {
        Integer limit = null;
        AddressesListBeforeAfterParameter beforeAfter = null;
        List<String> include = null;
        Map<String, String> dateCreated = null;
        Map<String, String> metadata = null;
        List<SelfMailerSize> size = null;
        Boolean scheduled = null;
        Object sendDate = null;
        MailType mailType = null;
        ChecksListSortByParameter sortBy = null;
        String campaignId = null;
        Status status = null;
        SelfMailersGetListResponse response = api.getList()
                .limit(limit)
                .beforeAfter(beforeAfter)
                .include(include)
                .dateCreated(dateCreated)
                .metadata(metadata)
                .size(size)
                .scheduled(scheduled)
                .sendDate(sendDate)
                .mailType(mailType)
                .sortBy(sortBy)
                .campaignId(campaignId)
                .status(status)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete
     *
     * Completely removes a self mailer from production. This can only be done if the self mailer&#39;s &#x60;send_date&#x60; has not yet passed. If the self mailer is successfully canceled, you will not be charged for it. This feature is exclusive to certain customers. Upgrade to the appropriate &lt;a href&#x3D;\&quot;https://dashboard.lob.com/#/settings/editions\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Print &amp; Mail Edition&lt;/a&gt; to gain access.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeSelfMailerTest() throws ApiException {
        String sfmId = null;
        SelfMailerDeletion response = api.removeSelfMailer(sfmId)
                .execute();
        // TODO: test validations
    }

}
